### ISSUE TITLE
Please tag release

### ISSUE THREAD

**Issue by ehaupt** [adplug/adplay-unix#5]
Could you please tag the releases. This would make it easier for packagers to move from the SF tarball to GH. Thanks.

**Comment by binarymaster** [comment]
Done! Check it out:

https://github.com/adplug/adplay-unix/releases

**Comment by ehaupt** [comment]
Thank you very much! I've just updated the FreeBSD ports for [libadplug](https://svnweb.freebsd.org/ports/head/audio/libadplug/), [adplay](https://svnweb.freebsd.org/ports/head/audio/adplay/), [libbinio](https://svnweb.freebsd.org/ports/head/devel/libbinio/). Any chance you could tag the adplug [database](https://github.com/adplug/database/releases) as well (it's currently tagged as 'import')? It would allow me to version the db file nicely instead of using the git commit hash.

**Comment by binarymaster** [comment]
> Any chance you could tag the adplug database as well (it's currently tagged as 'import')?

Ok, ready!

**Comment by ehaupt** [comment]
That was speedy! Thanks again.
